version: '3'

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ~/.ssh:/home/node/.ssh

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: sql@dev
      TZ: America/Porto_Velho
